---

- name: Log into proper cluster
  shell: oc login {{cluster1_openshift_host}} --token={{cluster1_openshift_token}} --insecure-skip-tls-verify=true

- name: Switch to proper project
  shell: oc project {{cluster1_jdg_project}}

- name: Get Stage LB address
  shell: ./roles/jdg-secrets/tasks/external-ip.sh
  register: _cluster1_lb_ip

- name: Log into proper cluster
  shell: oc login {{cluster2_openshift_host}} --token={{cluster2_openshift_token}} --insecure-skip-tls-verify=true

- name: Switch to proper project
  shell: oc project {{cluster2_jdg_project}}

- name: Get AWS LB address
  shell: ./roles/jdg-secrets/tasks/external-ip.sh
  register: _cluster2_lb_ip

- debug:
    msg: "Cluster1 IP {{ _cluster1_lb_ip.stdout }}, Cluster2 IP {{ _cluster2_lb_ip.stdout }}"

- name: Setting secret values for Stage cluster
  set_fact:
    openshift_host: "{{ cluster1_openshift_host }}"
    openshift_token: "{{ cluster1_openshift_token }}"
    jdg_project: "{{ cluster1_jdg_project }}"
    site: "cluster1"
    external_address: "{{ _cluster1_lb_ip.stdout }}"
    discovery_string: "{{ _cluster1_lb_ip.stdout }}[55200],{{ _cluster2_lb_ip.stdout }}[55200]"

- debug:
    msg: "State External address {{ external_address }}, discovery string {{ discovery_string }}"

- include: create-secret.yml

- name: Setting secret values for AWS cluster
  set_fact:
    openshift_host: "{{ cluster2_openshift_host }}"
    openshift_token: "{{ cluster2_openshift_token }}"
    jdg_project: "{{ cluster2_jdg_project }}"
    site: "cluster2"
    external_address: "{{ _cluster2_lb_ip.stdout }}"
    discovery_string: "{{ _cluster1_lb_ip.stdout }}[55200],{{ _cluster2_lb_ip.stdout }}[55200]"

- debug:
    msg: "State External address {{ external_address }}, discovery string {{ discovery_string }}"

- include: create-secret.yml
